version: '3'
services:
  frontend-builder:
    build: frontend/docker-dev/builder
    user: $UID:$GID
    volumes:
      - type: bind
        source: ./
        target: /workspace/bindpoint
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
  frontend-runner:
    build: frontend/docker-dev/runner
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./frontend/build-dev
        target: /usr/share/nginx/html/
      - type: bind
        source: ./frontend/conf/conf.d
        target: /etc/nginx/conf.d/
  frontend-imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      - IMGPROXY_BIND=0.0.0.0:8082
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_DEVELOPMENT_ERRORS_MODE=true
    network_mode: host