version: '3.2'
services:
  frontend-imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      - IMGPROXY_BIND=0.0.0.0:8082
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_DEVELOPMENT_ERRORS_MODE=true
    network_mode: host